Repository MafraqLTD/Mafraq, pull requests merged in 2024-04, with the labels that each got.

#1 map-destination
  presentation/src/main/java/com/mafraq/presentation/design/components/BottomSheet.kt
  presentation/src/main/java/com/mafraq/presentation/features/home/HomeScreen.kt
  presentation/src/main/java/com/mafraq/presentation/features/map/components/DestinationBottomSheet.kt
  presentation/src/main/res/drawable/ic_gps.xml
  presentation/src/main/res/drawable/ic_location.xml
  presentation/src/main/res/values-ar/strings.xml
  presentation/src/main/res/values/strings.xml
Labels: feature

#4 implement-retable-api
  app/src/main/java/com/mafraq/Constants.kt
  app/src/main/java/com/mafraq/di/DataSourceModule.kt
  app/src/main/java/com/mafraq/di/RemoteApiModule.kt
  app/src/main/java/com/mafraq/di/RepositoryModule.kt
  buildSrc/src/main/kotlin/extensions.kt
  data/build.gradle.kts
  data/src/main/java/com/mafraq/data/entities/ApiResponse.kt
  data/src/main/java/com/mafraq/data/entities/login/AuthUser.kt
  data/src/main/java/com/mafraq/data/entities/login/LoginResponse.kt
  data/src/main/java/com/mafraq/data/entities/map/Driver.kt
  data/src/main/java/com/mafraq/data/models/ApiResponseDto.kt
  data/src/main/java/com/mafraq/data/remote/dataSource/.keep
  data/src/main/java/com/mafraq/data/remote/dataSource/crm/CRMRemoteDataSource.kt
  data/src/main/java/com/mafraq/data/remote/dataSource/crm/CRMRemoteDataSourceImpl.kt
  data/src/main/java/com/mafraq/data/remote/dataSource/user/FirebaseAuthDataSource.kt
  data/src/main/java/com/mafraq/data/remote/dataSource/user/FirebaseAuthDataSourceImpl.kt
  data/src/main/java/com/mafraq/data/remote/interceptor/HeaderInterceptor.kt
  data/src/main/java/com/mafraq/data/remote/mappers/ApiResponseFromDtoMapper.kt
  data/src/main/java/com/mafraq/data/remote/mappers/DriverFromRemoteMapper.kt
  data/src/main/java/com/mafraq/data/remote/mappers/UserAuthFromRemoteMapper.kt
  data/src/main/java/com/mafraq/data/remote/mappers/extensions.kt
  data/src/main/java/com/mafraq/data/remote/models/ApiResponseDto.kt
  data/src/main/java/com/mafraq/data/remote/models/DriverRemote.kt
  data/src/main/java/com/mafraq/data/remote/models/LocationRemote.kt
  data/src/main/java/com/mafraq/data/remote/service/LocationDeserializer.kt
  data/src/main/java/com/mafraq/data/remote/service/RetableService.kt
  data/src/main/java/com/mafraq/data/repository/crm/CRMRepository.kt
  data/src/main/java/com/mafraq/data/repository/crm/CRMRepositoryImpl.kt
  data/src/main/java/com/mafraq/data/repository/user/UserRepository.kt
  data/src/main/java/com/mafraq/data/repository/user/UserRepositoryImpl.kt
  data/src/main/java/com/mafraq/data/service/.keep
  data/src/main/java/com/mafraq/data/utils/extensions.kt
  gradle/libs.versions.toml
  presentation/src/main/java/com/mafraq/presentation/design/components/BottomSheet.kt
  presentation/src/main/java/com/mafraq/presentation/features/base/BaseViewModel.kt
  presentation/src/main/java/com/mafraq/presentation/features/map/MapScreen.kt
  presentation/src/main/java/com/mafraq/presentation/features/map/MapUiState.kt
  presentation/src/main/java/com/mafraq/presentation/features/map/MapViewModel.kt
  presentation/src/main/java/com/mafraq/presentation/features/map/components/DestinationBottomSheet.kt
  presentation/src/main/java/com/mafraq/presentation/features/map/components/DriverBottomSheet.kt
  presentation/src/main/java/com/mafraq/presentation/features/map/components/MapScreenWithMarkers.kt
  presentation/src/main/java/com/mafraq/presentation/utils/RememberLocationRequester.kt
Labels: enhancement, feature

#20 implement-ads
  buildSrc/src/main/kotlin/extensions.kt
  data/build.gradle.kts
  data/src/main/java/com/mafraq/data/entities/ApiResponse.kt
  data/src/main/java/com/mafraq/data/entities/home/Ad.kt
  data/src/main/java/com/mafraq/data/remote/dataSource/crm/CRMRemoteDataSource.kt
  data/src/main/java/com/mafraq/data/remote/dataSource/crm/CRMRemoteDataSourceImpl.kt
  data/src/main/java/com/mafraq/data/remote/mappers/AdFromRemoteMapper.kt
  data/src/main/java/com/mafraq/data/remote/mappers/ApiResponseFromDtoMapper.kt
  data/src/main/java/com/mafraq/data/remote/models/AdRemote.kt
  data/src/main/java/com/mafraq/data/remote/models/ApiResponseDto.kt
  data/src/main/java/com/mafraq/data/remote/models/ApiResponseRemote.kt
  data/src/main/java/com/mafraq/data/remote/service/RetableService.kt
  data/src/main/java/com/mafraq/data/repository/crm/CRMRepository.kt
  data/src/main/java/com/mafraq/data/repository/crm/CRMRepositoryImpl.kt
  defaults.properties
  presentation/src/main/java/com/mafraq/presentation/features/base/BaseViewModel.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/ChatScreen.kt
  presentation/src/main/java/com/mafraq/presentation/features/home/HomeUiState.kt
  presentation/src/main/java/com/mafraq/presentation/features/home/HomeViewModel.kt
  presentation/src/main/java/com/mafraq/presentation/features/home/components/AdsCarouselCard.kt
  presentation/src/main/java/com/mafraq/presentation/utils/dummyData/Dummy.kt
Labels: feature

#21 improve-driver-implementation
  app/src/main/java/com/mafraq/di/RemoteApiModule.kt
  data/src/main/java/com/mafraq/data/entities/SeparatedValuesListOfString.kt
  data/src/main/java/com/mafraq/data/entities/Subscriber.kt
  data/src/main/java/com/mafraq/data/entities/map/Driver.kt
  data/src/main/java/com/mafraq/data/entities/map/SubscriptionStatus.kt
  data/src/main/java/com/mafraq/data/remote/mappers/DriverFromRemoteMapper.kt
  data/src/main/java/com/mafraq/data/remote/mappers/extensions.kt
  data/src/main/java/com/mafraq/data/remote/models/DriverRemote.kt
  data/src/main/java/com/mafraq/data/utils/convertors/LocationDeserializer.kt
  data/src/main/java/com/mafraq/data/utils/convertors/SeparatedValuesListOfStringDeserializer.kt
  data/src/main/java/com/mafraq/data/utils/extensions.kt
Labels: enhancement

#23 Implement chat logic
  .github/workflows/android.yaml
  app/src/main/java/com/mafraq/di/AppModule.kt
  app/src/main/java/com/mafraq/di/DataSourceModule.kt
  app/src/main/java/com/mafraq/di/RepositoryModule.kt
  data/src/main/java/com/mafraq/data/entities/Session.kt
  data/src/main/java/com/mafraq/data/entities/chat/Message.kt
  data/src/main/java/com/mafraq/data/local/location/LocationDataSource.kt
  data/src/main/java/com/mafraq/data/local/location/LocationDataSourceImpl.kt
  data/src/main/java/com/mafraq/data/local/session/SessionLocalDataSource.kt
  data/src/main/java/com/mafraq/data/local/session/SessionLocalDataSourceImpl.kt
  data/src/main/java/com/mafraq/data/remote/dataSource/chat/FirebaseFireStoreDelegation.kt
  data/src/main/java/com/mafraq/data/remote/dataSource/chat/FirebaseFireStoreDelegationImpl.kt
  data/src/main/java/com/mafraq/data/remote/dataSource/chat/FirestoreExtensions.kt
  data/src/main/java/com/mafraq/data/remote/dataSource/crm/CRMRemoteDataSource.kt
  data/src/main/java/com/mafraq/data/remote/dataSource/crm/CRMRemoteDataSourceImpl.kt
  data/src/main/java/com/mafraq/data/remote/errors/DeleteException.kt
  data/src/main/java/com/mafraq/data/remote/errors/FetchException.kt
  data/src/main/java/com/mafraq/data/remote/errors/InsertException.kt
  data/src/main/java/com/mafraq/data/repository/chat/group/GroupChatRepository.kt
  data/src/main/java/com/mafraq/data/repository/chat/group/GroupChatRepositoryImpl.kt
  data/src/main/java/com/mafraq/data/repository/chat/support/SupportChatRepository.kt
  data/src/main/java/com/mafraq/data/repository/chat/support/SupportChatRepositoryImpl.kt
  data/src/main/java/com/mafraq/data/repository/crm/CRMRepository.kt
  data/src/main/java/com/mafraq/data/repository/crm/CRMRepositoryImpl.kt
  data/src/main/java/com/mafraq/data/repository/hardware/HardwareRepository.kt
  data/src/main/java/com/mafraq/data/repository/hardware/HardwareRepositoryImpl.kt
  data/src/main/java/com/mafraq/data/utils/extensions.kt
  gradle/libs.versions.toml
  presentation/src/main/java/com/mafraq/presentation/features/chat/components/MessageItem.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/group/ChatGroupEvent.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/group/ChatGroupInteractionListener.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/group/ChatGroupScreen.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/group/ChatGroupViewModel.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/support/ChatSupportInteractionListener.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/support/ChatSupportScreen.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/support/ChatSupportViewModel.kt
  presentation/src/main/java/com/mafraq/presentation/utils/dummyData/Dummy.kt
Labels: feature

#24 add search component result for search Destination screen
  presentation/src/main/java/com/mafraq/presentation/design/components/ColumnPreview.kt
  presentation/src/main/java/com/mafraq/presentation/features/home/components/SearchResultItem.kt
  presentation/src/main/res/drawable/ic_location_filled.xml
Labels: enhancement

#25 Implement support chat
  app/src/main/java/com/mafraq/di/DataSourceModule.kt
  app/src/main/java/com/mafraq/di/RepositoryModule.kt
  data/src/main/java/com/mafraq/data/entities/Subscriber.kt
  data/src/main/java/com/mafraq/data/entities/chat/ChatMember.kt
  data/src/main/java/com/mafraq/data/entities/chat/Message.kt
  data/src/main/java/com/mafraq/data/remote/dataSource/auth/FirebaseAuthDataSource.kt
  data/src/main/java/com/mafraq/data/remote/dataSource/auth/FirebaseAuthDataSourceImpl.kt
  data/src/main/java/com/mafraq/data/remote/dataSource/chat/FirebaseFireStoreDelegation.kt
  data/src/main/java/com/mafraq/data/remote/dataSource/chat/FirebaseFireStoreDelegationImpl.kt
  data/src/main/java/com/mafraq/data/remote/dataSource/chat/FirebaseFireStoreMessenger.kt
  data/src/main/java/com/mafraq/data/remote/dataSource/chat/FirestoreExtensions.kt
  data/src/main/java/com/mafraq/data/remote/dataSource/user/SubscriptionDataSource.kt
  data/src/main/java/com/mafraq/data/remote/mappers/MessageFromRemoteMapper.kt
  data/src/main/java/com/mafraq/data/remote/mappers/MessageToRemoteMapper.kt
  data/src/main/java/com/mafraq/data/remote/models/chat/MessageRemote.kt
  data/src/main/java/com/mafraq/data/repository/auth/AuthRepository.kt
  data/src/main/java/com/mafraq/data/repository/auth/AuthRepositoryImpl.kt
  data/src/main/java/com/mafraq/data/repository/chat/group/GroupChatRepository.kt
  data/src/main/java/com/mafraq/data/repository/chat/group/GroupChatRepositoryImpl.kt
  data/src/main/java/com/mafraq/data/repository/chat/support/SupportChatRepository.kt
  data/src/main/java/com/mafraq/data/repository/chat/support/SupportChatRepositoryImpl.kt
  data/src/main/java/com/mafraq/data/utils/extensions.kt
  presentation/src/main/java/com/mafraq/presentation/features/authentication/viewmodel/AuthViewModel.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/components/ChatSupportHeader.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/components/MessageItem.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/group/ChatGroupScreen.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/group/ChatGroupViewModel.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/support/ChatSupportScreen.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/support/ChatSupportUiState.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/support/ChatSupportViewModel.kt
  presentation/src/main/java/com/mafraq/presentation/features/home/HomeViewModel.kt
  presentation/src/main/java/com/mafraq/presentation/features/main/MainActivity.kt
Labels: feature

#28 Implement chat context menu
  data/src/main/java/com/mafraq/data/entities/chat/Message.kt
  data/src/main/java/com/mafraq/data/local/session/SessionLocalDataSourceImpl.kt
  data/src/main/java/com/mafraq/data/remote/dataSource/chat/FirestoreExtensions.kt
  data/src/main/java/com/mafraq/data/remote/models/chat/MessageRemote.kt
  data/src/main/java/com/mafraq/data/utils/extensions.kt
  gradle/libs.versions.toml
  presentation/src/main/java/com/mafraq/presentation/design/components/AppOutlinedTextField.kt
  presentation/src/main/java/com/mafraq/presentation/design/theme/Typography.kt
  presentation/src/main/java/com/mafraq/presentation/features/base/BaseViewModel.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/ChatInteractionListener.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/components/ChatScreenTemplate.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/components/ContextMenu.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/components/EditMessageBanner.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/components/MessageItem.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/components/MessageItemWithContextMenu.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/group/ChatGroupInteractionListener.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/group/ChatGroupScreen.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/group/GroupChatContextMenuAction.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/support/ChatSupportInteractionListener.kt
  presentation/src/main/java/com/mafraq/presentation/features/chat/support/ChatSupportScreen.kt
  presentation/src/main/res/drawable/ic_check_square.xml
  presentation/src/main/res/drawable/ic_edit.xml
  presentation/src/main/res/drawable/ic_verified.xml
  presentation/src/main/res/values-ar/strings.xml
  presentation/src/main/res/values/strings.xml
Labels: feature

#30 Implement map search
  app/build.gradle.kts
  app/src/main/java/com/mafraq/MafraqApplication.kt
  app/src/main/java/com/mafraq/di/AppModule.kt
  app/src/main/java/com/mafraq/di/DataSourceModule.kt
  app/src/main/java/com/mafraq/di/RepositoryModule.kt
  buildSrc/src/main/kotlin/extensions.kt
  data/src/main/java/com/mafraq/data/entities/map/PlaceSuggestion.kt
  data/src/main/java/com/mafraq/data/remote/dataSource/map/GooglePlacesDataSource.kt
  data/src/main/java/com/mafraq/data/remote/dataSource/map/GooglePlacesDataSourceImpl.kt
  data/src/main/java/com/mafraq/data/remote/mappers/PlaceSuggestionMapper.kt
  data/src/main/java/com/mafraq/data/repository/map/MapPlacesRepository.kt
  data/src/main/java/com/mafraq/data/repository/map/MapPlacesRepositoryImpl.kt
  defaults.properties
  gradle/libs.versions.toml
  presentation/src/main/java/com/mafraq/presentation/features/home/HomeEvent.kt
  presentation/src/main/java/com/mafraq/presentation/features/home/HomeInteractionListener.kt
  presentation/src/main/java/com/mafraq/presentation/features/home/HomeScreen.kt
  presentation/src/main/java/com/mafraq/presentation/features/home/HomeUiState.kt
  presentation/src/main/java/com/mafraq/presentation/features/home/HomeViewModel.kt
  presentation/src/main/java/com/mafraq/presentation/features/home/components/SearchResultItem.kt
  presentation/src/main/java/com/mafraq/presentation/features/main/App.kt
  presentation/src/main/java/com/mafraq/presentation/features/map/MapInteractionListener.kt
  presentation/src/main/java/com/mafraq/presentation/features/map/MapScreen.kt
  presentation/src/main/java/com/mafraq/presentation/features/map/MapUiState.kt
  presentation/src/main/java/com/mafraq/presentation/features/map/MapViewModel.kt
  presentation/src/main/java/com/mafraq/presentation/features/map/components/MapScreenWithMarkers.kt
  presentation/src/main/java/com/mafraq/presentation/navigation/MapScreenArgs.kt
  presentation/src/main/java/com/mafraq/presentation/navigation/Screen.kt
  presentation/src/main/java/com/mafraq/presentation/navigation/destinations/MapDestination.kt
  presentation/src/main/java/com/mafraq/presentation/utils/extensions/mapper.kt
  presentation/src/main/java/com/mafraq/presentation/utils/extensions/navExtensions.kt
  presentation/src/main/res/values-ar/strings.xml
  presentation/src/main/res/values/strings.xml
Labels: feature
